INSERT INTO `#__claw_field_values` (`id`, `fieldname`, `value`, `text`) VALUES
(0, 'skill_time_slot', '0930:060', '9:30AM - 60 minutes'),
(0, 'skill_time_slot', '1100:090', '11:00AM - 90 minutes'),
(0, 'skill_time_slot', '1400:090', '2:00PM - 90 minutes (Sun)'),
(0, 'skill_time_slot', '1400:120', '2:00PM - 120 minutes'),
(0, 'skill_time_slot', '1630:060', '4:30PM - 60 minutes'),
(0, 'skill_class_type', 'demo', 'Demo'),
(0, 'skill_class_type', 'lecture', 'Lecture'),
(0, 'skill_class_type', 'round', 'Round Table'),
(0, 'skill_class_type', 'panel', 'Panel'),
(0, 'shift_shift_area', 'guestservices', 'Guest Services'),
(0, 'shift_shift_area', 'facilities', 'Facilities'),
(0, 'shift_shift_area', 'se', 'Skills & Education'),
(0, 'shift_shift_area', 'badgecheck', 'Badge Check'),
(0, 'shift_shift_area', 'events', 'Events'),
(0, 'shift_shift_area', 'volhosp', 'Volunteer Hospitality'),
(0, 'shift_shift_area', 'silentauction', 'Silent Auction'),
(0, 'shift_shift_area', 'artshow', 'Art Show'),
(0, 'shift_shift_area', 'specialty', 'Specialty'),
(0, 'shift_shift_area', 'float', 'Float'),
(0, 'shift_shift_area', 'tbd', 'TBD');
