INSERT INTO `#__claw_field_values` (`id`, `fieldname`, `value`, `text`) VALUES
(0, 'skill_time_slot', '0930:060', '9:30AM - 60 minutes'),
(0, 'skill_time_slot', '1100:090', '11:00AM - 90 minutes'),
(0, 'skill_time_slot', '1400:090', '2:00PM - 90 minutes (Sun)'),
(0, 'skill_time_slot', '1400:120', '2:00PM - 120 minutes'),
(0, 'skill_time_slot', '1630:060', '4:30PM - 60 minutes'),
(0, 'skill_class_type', 'demo', 'Demo'),
(0, 'skill_class_type', 'lecture', 'Lecture'),
(0, 'skill_class_type', 'round', 'Round Table'),
(0, 'skill_class_type', 'panel', 'Panel'),
(0, 'skill_category', 'assplay', 'Ass Play/Sex'),
(0, 'skill_category', 'bondage', 'Bondage'),
(0, 'skill_category', 'community', 'Community'),
(0, 'skill_category', 'fetish', 'Fetish'),
(0, 'skill_category', 'gear', 'Gear'),
(0, 'skill_category', 'health', 'Health'),
(0, 'skill_category', 'powerdynamics', 'Power Dynamics'),
(0, 'skill_category', 'sex', 'Sex'),
(0, 'skill_category', 'sm', 'SM'),
(0, 'skill_track', 'caras', 'CARAS'),
(0, 'shift_shift_area', 'guestservices', 'Guest Services'),
(0, 'shift_shift_area', 'facilities', 'Facilities'),
(0, 'shift_shift_area', 'se', 'Skills & Education'),
(0, 'shift_shift_area', 'badgecheck', 'Badge Check'),
(0, 'shift_shift_area', 'events', 'Events'),
(0, 'shift_shift_area', 'hospitality', 'Volunteer Hospitality'),
(0, 'shift_shift_area', 'silentauction', 'Silent Auction'),
(0, 'shift_shift_area', 'artshow', 'Art Show'),
(0, 'shift_shift_area', 'specialty', 'Specialty'),
(0, 'shift_shift_area', 'float', 'Float'),
(0, 'shift_shift_area', 'tbd', 'TBD'),
(0, 'config_shift_category', 'shifts-artshow', 'shifts-artshow'),
(0, 'config_shift_category', 'shifts-badgecheck', 'shifts-badgecheck'),
(0, 'config_shift_category', 'shifts-events', 'shifts-events'),
(0, 'config_shift_category', 'shifts-facilities', 'shifts-facilities'),
(0, 'config_shift_category', 'shifts-float', 'shifts-float'),
(0, 'config_shift_category', 'shifts-guestservices', 'shifts-guestservices'),
(0, 'config_shift_category', 'shifts-hospitality', 'shifts-hospitality' ),
(0, 'config_shift_category', 'shifts-se', 'shifts-se'),
(0, 'config_shift_category', 'shifts-silentauction', 'shifts-silentauction'),
(0, 'config_shift_category', 'shifts-specialty', 'shifts-specialty'),
(0, 'config_urlprefix', 'base', '/claw-all-events/'),
(0, 'config_urlprefix', 'shifts', '/claw-all-events/shifts/'),
(0, 'config_debug_email', 'email', 'webmaster@clawinfo.org'),
(0, 'config_timezone', 'server', 'America/Chicago'),
(0, 'config_images', 'sponsor_icons', '/images/0_static_graphics/sponsors/100'),
(0, 'config_images', 'ads', '/images/0_static_graphics/ads'),
(0, 'config_images', 'presenters', '/images/skills/presenters'),
(0, 'config_overlap_category', 'shifts-artshow', 'shifts-artshow'),
(0, 'config_overlap_category', 'shifts-badgecheck', 'shifts-badgecheck'),
(0, 'config_overlap_category', 'shifts-events', 'shifts-events'),
(0, 'config_overlap_category', 'shifts-facilities', 'shifts-facilities'),
(0, 'config_overlap_category', 'shifts-float', 'shifts-float'),
(0, 'config_overlap_category', 'shifts-guestservices', 'shifts-guestservices'),
(0, 'config_overlap_category', 'shifts-hospitality', 'shifts-hospitality' ),
(0, 'config_overlap_category', 'shifts-se', 'shifts-se'),
(0, 'config_overlap_category', 'shifts-silentauction', 'shifts-silentauction'),
(0, 'config_overlap_category', 'shifts-specialty', 'shifts-specialty'),
(0, 'config_overlap_category', 'speed-dating', 'speed-dating'),
(0, 'config_overlap_category', 'dinner', 'dinner'),
(0, 'config_overlap_category', 'buffet', 'buffet'),
(0, 'config_overlap_category', 'buffet-breakfast', 'buffet-breakfast'),
