INSERT INTO `#__claw_field_values` (`id`, `fieldname`, `value`, `text`, `event`) VALUES
(0, 'skill_time_slot', '0930:060', '9:30AM - 60 minutes', 'c0424'),
(0, 'skill_time_slot', '1100:090', '11:00AM - 90 minutes', 'c0424'),
(0, 'skill_time_slot', '1400:090', '2:00PM - 90 minutes (Sun)', 'c0424'),
(0, 'skill_time_slot', '1400:120', '2:00PM - 120 minutes', 'c0424'),
(0, 'skill_time_slot', '1630:060', '4:30PM - 60 minutes', 'c0424'),
(0, 'skill_class_type', 'demo', 'Demo', 'c0424'),
(0, 'skill_class_type', 'lecture', 'Lecture', 'c0424'),
(0, 'skill_class_type', 'round', 'Round Table', 'c0424'),
(0, 'skill_class_type', 'panel', 'Panel', 'c0424'),
(0, 'skill_class_type', 'workshop', 'Workshop', 'c0424'),
(0, 'skill_category', 'assplay', 'Ass Play/Sex', 'c0424'),
(0, 'skill_category', 'bondage', 'Bondage', 'c0424'),
(0, 'skill_category', 'community', 'Community', 'c0424'),
(0, 'skill_category', 'fetish', 'Fetish', 'c0424'),
(0, 'skill_category', 'gear', 'Gear', 'c0424'),
(0, 'skill_category', 'health', 'Health', 'c0424'),
(0, 'skill_category', 'powerdynamics', 'Power Dynamics', 'c0424'),
(0, 'skill_category', 'sex', 'Sex', 'c0424'),
(0, 'skill_category', 'sm', 'SM', 'c0424'),
(0, 'skill_track', 'caras', 'CARAS', 'c0424'),
(0, 'shift_shift_area', 'guestservices', 'Guest Services', 'c0424'),
(0, 'shift_shift_area', 'facilities', 'Facilities', 'c0424'),
(0, 'shift_shift_area', 'se', 'Skills & Education', 'c0424'),
(0, 'shift_shift_area', 'badgecheck', 'Badge Check', 'c0424'),
(0, 'shift_shift_area', 'events', 'Events', 'c0424'),
(0, 'shift_shift_area', 'hospitality', 'Volunteer Hospitality', 'c0424'),
(0, 'shift_shift_area', 'silentauction', 'Silent Auction', 'c0424'),
(0, 'shift_shift_area', 'artshow', 'Art Show', 'c0424'),
(0, 'shift_shift_area', 'specialty', 'Specialty', 'c0424'),
(0, 'shift_shift_area', 'float', 'Float', 'c0424'),
(0, 'shift_shift_area', 'tbd', 'TBD', 'c0424'),
(0, 'config_urlprefix', 'shifts', '/claw-all-events/shifts/', 'c0424'),
(0, 'config_debug_email', 'email', 'webmaster@clawinfo.org', 'c0424'),
(0, 'config_timezone', 'server', 'America/Chicago', 'c0424'),
(0, 'config_images', 'sponsor_icons', '/images/0_static_graphics/sponsors/100', 'c0424'),
(0, 'config_images', 'ads', '/images/0_static_graphics/ads', 'c0424'),
(0, 'config_images', 'presenters', '/images/skills/presenters', 'c0424'),
(0, 'config_overlap_category', 'shifts-artshow', 'shifts-artshow', 'c0424'),
(0, 'config_overlap_category', 'shifts-badgecheck', 'shifts-badgecheck', 'c0424'),
(0, 'config_overlap_category', 'shifts-events', 'shifts-events', 'c0424'),
(0, 'config_overlap_category', 'shifts-facilities', 'shifts-facilities', 'c0424'),
(0, 'config_overlap_category', 'shifts-float', 'shifts-float', 'c0424'),
(0, 'config_overlap_category', 'shifts-guestservices', 'shifts-guestservices', 'c0424'),
(0, 'config_overlap_category', 'shifts-hospitality', 'shifts-hospitality' , 'c0424'),
(0, 'config_overlap_category', 'shifts-se', 'shifts-se', 'c0424'),
(0, 'config_overlap_category', 'shifts-silentauction', 'shifts-silentauction', 'c0424'),
(0, 'config_overlap_category', 'shifts-specialty', 'shifts-specialty', 'c0424'),
(0, 'config_overlap_category', 'speed-dating', 'speed-dating', 'c0424'),
(0, 'config_overlap_category', 'dinner', 'dinner', 'c0424'),
(0, 'config_overlap_category', 'buffet', 'buffet', 'c0424'),
(0, 'config_overlap_category', 'buffet-breakfast', 'buffet-breakfast', 'c0424'),

(0, 'skill_time_slot', '0930:060', '9:30AM - 60 minutes', 'l1123'),
(0, 'skill_time_slot', '1100:090', '11:00AM - 90 minutes', 'l1123'),
(0, 'skill_time_slot', '1400:090', '2:00PM - 90 minutes (Sun)', 'l1123'),
(0, 'skill_time_slot', '1400:120', '2:00PM - 120 minutes', 'l1123'),
(0, 'skill_time_slot', '1630:060', '4:30PM - 60 minutes', 'l1123'),
(0, 'skill_class_type', 'demo', 'Demo', 'l1123'),
(0, 'skill_class_type', 'lecture', 'Lecture', 'l1123'),
(0, 'skill_class_type', 'round', 'Round Table', 'l1123'),
(0, 'skill_class_type', 'panel', 'Panel', 'l1123'),
(0, 'skill_class_type', 'workshop', 'Workshop', 'l1123'),
(0, 'skill_category', 'assplay', 'Ass Play/Sex', 'l1123'),
(0, 'skill_category', 'bondage', 'Bondage', 'l1123'),
(0, 'skill_category', 'community', 'Community', 'l1123'),
(0, 'skill_category', 'fetish', 'Fetish', 'l1123'),
(0, 'skill_category', 'gear', 'Gear', 'l1123'),
(0, 'skill_category', 'health', 'Health', 'l1123'),
(0, 'skill_category', 'powerdynamics', 'Power Dynamics', 'l1123'),
(0, 'skill_category', 'sex', 'Sex', 'l1123'),
(0, 'skill_category', 'sm', 'SM', 'l1123'),
(0, 'skill_track', 'caras', 'CARAS', 'l1123'),
(0, 'shift_shift_area', 'guestservices', 'Guest Services', 'l1123'),
(0, 'shift_shift_area', 'facilities', 'Facilities', 'l1123'),
(0, 'shift_shift_area', 'se', 'Skills & Education', 'l1123'),
(0, 'shift_shift_area', 'badgecheck', 'Badge Check', 'l1123'),
(0, 'shift_shift_area', 'events', 'Events', 'l1123'),
(0, 'shift_shift_area', 'hospitality', 'Volunteer Hospitality', 'l1123'),
(0, 'shift_shift_area', 'silentauction', 'Silent Auction', 'l1123'),
(0, 'shift_shift_area', 'artshow', 'Art Show', 'l1123'),
(0, 'shift_shift_area', 'specialty', 'Specialty', 'l1123'),
(0, 'shift_shift_area', 'float', 'Float', 'l1123'),
(0, 'shift_shift_area', 'tbd', 'TBD', 'l1123'),
(0, 'config_urlprefix', 'shifts', '/claw-all-events/shifts/', 'l1123'),
(0, 'config_debug_email', 'email', 'webmaster@clawinfo.org', 'l1123'),
(0, 'config_timezone', 'server', 'America/Chicago', 'l1123'),
(0, 'config_images', 'sponsor_icons', '/images/0_static_graphics/sponsors/100', 'l1123'),
(0, 'config_images', 'ads', '/images/0_static_graphics/ads', 'l1123'),
(0, 'config_images', 'presenters', '/images/skills/presenters', 'l1123'),
(0, 'config_overlap_category', 'shifts-artshow', 'shifts-artshow', 'l1123'),
(0, 'config_overlap_category', 'shifts-badgecheck', 'shifts-badgecheck', 'l1123'),
(0, 'config_overlap_category', 'shifts-events', 'shifts-events', 'l1123'),
(0, 'config_overlap_category', 'shifts-facilities', 'shifts-facilities', 'l1123'),
(0, 'config_overlap_category', 'shifts-float', 'shifts-float', 'l1123'),
(0, 'config_overlap_category', 'shifts-guestservices', 'shifts-guestservices', 'l1123'),
(0, 'config_overlap_category', 'shifts-hospitality', 'shifts-hospitality' , 'l1123'),
(0, 'config_overlap_category', 'shifts-se', 'shifts-se', 'l1123'),
(0, 'config_overlap_category', 'shifts-silentauction', 'shifts-silentauction', 'l1123'),
(0, 'config_overlap_category', 'shifts-specialty', 'shifts-specialty', 'l1123'),
(0, 'config_overlap_category', 'speed-dating', 'speed-dating', 'l1123'),
(0, 'config_overlap_category', 'dinner', 'dinner', 'l1123'),
(0, 'config_overlap_category', 'buffet', 'buffet', 'l1123'),
(0, 'config_overlap_category', 'buffet-breakfast', 'buffet-breakfast', 'l1123'),

(0, 'skill_time_slot', '0930:060', '9:30AM - 60 minutes', 'c0423'),
(0, 'skill_time_slot', '1100:090', '11:00AM - 90 minutes', 'c0423'),
(0, 'skill_time_slot', '1400:090', '2:00PM - 90 minutes (Sun)', 'c0423'),
(0, 'skill_time_slot', '1400:120', '2:00PM - 120 minutes', 'c0423'),
(0, 'skill_time_slot', '1630:060', '4:30PM - 60 minutes', 'c0423'),
(0, 'skill_class_type', 'demo', 'Demo', 'c0423'),
(0, 'skill_class_type', 'lecture', 'Lecture', 'c0423'),
(0, 'skill_class_type', 'round', 'Round Table', 'c0423'),
(0, 'skill_class_type', 'panel', 'Panel', 'c0423'),
(0, 'skill_class_type', 'workshop', 'Workshop', 'c0423'),
(0, 'skill_category', 'assplay', 'Ass Play/Sex', 'c0423'),
(0, 'skill_category', 'bondage', 'Bondage', 'c0423'),
(0, 'skill_category', 'community', 'Community', 'c0423'),
(0, 'skill_category', 'fetish', 'Fetish', 'c0423'),
(0, 'skill_category', 'gear', 'Gear', 'c0423'),
(0, 'skill_category', 'health', 'Health', 'c0423'),
(0, 'skill_category', 'powerdynamics', 'Power Dynamics', 'c0423'),
(0, 'skill_category', 'sex', 'Sex', 'c0423'),
(0, 'skill_category', 'sm', 'SM', 'c0423'),
(0, 'skill_track', 'caras', 'CARAS', 'c0423'),
(0, 'shift_shift_area', 'guestservices', 'Guest Services', 'c0423'),
(0, 'shift_shift_area', 'facilities', 'Facilities', 'c0423'),
(0, 'shift_shift_area', 'se', 'Skills & Education', 'c0423'),
(0, 'shift_shift_area', 'badgecheck', 'Badge Check', 'c0423'),
(0, 'shift_shift_area', 'events', 'Events', 'c0423'),
(0, 'shift_shift_area', 'hospitality', 'Volunteer Hospitality', 'c0423'),
(0, 'shift_shift_area', 'silentauction', 'Silent Auction', 'c0423'),
(0, 'shift_shift_area', 'artshow', 'Art Show', 'c0423'),
(0, 'shift_shift_area', 'specialty', 'Specialty', 'c0423'),
(0, 'shift_shift_area', 'float', 'Float', 'c0423'),
(0, 'shift_shift_area', 'tbd', 'TBD', 'c0423'),
(0, 'config_urlprefix', 'shifts', '/claw-all-events/shifts/', 'c0423'),
(0, 'config_debug_email', 'email', 'webmaster@clawinfo.org', 'c0423'),
(0, 'config_timezone', 'server', 'America/Chicago', 'c0423'),
(0, 'config_images', 'sponsor_icons', '/images/0_static_graphics/sponsors/100', 'c0423'),
(0, 'config_images', 'ads', '/images/0_static_graphics/ads', 'c0423'),
(0, 'config_images', 'presenters', '/images/skills/presenters', 'c0423'),
(0, 'config_overlap_category', 'shifts-artshow', 'shifts-artshow', 'c0423'),
(0, 'config_overlap_category', 'shifts-badgecheck', 'shifts-badgecheck', 'c0423'),
(0, 'config_overlap_category', 'shifts-events', 'shifts-events', 'c0423'),
(0, 'config_overlap_category', 'shifts-facilities', 'shifts-facilities', 'c0423'),
(0, 'config_overlap_category', 'shifts-float', 'shifts-float', 'c0423'),
(0, 'config_overlap_category', 'shifts-guestservices', 'shifts-guestservices', 'c0423'),
(0, 'config_overlap_category', 'shifts-hospitality', 'shifts-hospitality' , 'c0423'),
(0, 'config_overlap_category', 'shifts-se', 'shifts-se', 'c0423'),
(0, 'config_overlap_category', 'shifts-silentauction', 'shifts-silentauction', 'c0423'),
(0, 'config_overlap_category', 'shifts-specialty', 'shifts-specialty', 'c0423'),
(0, 'config_overlap_category', 'speed-dating', 'speed-dating', 'c0423'),
(0, 'config_overlap_category', 'dinner', 'dinner', 'c0423'),
(0, 'config_overlap_category', 'buffet', 'buffet', 'c0423'),
(0, 'config_overlap_category', 'buffet-breakfast', 'buffet-breakfast', 'c0423')
;
